### ISSUE TITLE
IKEA TRÅDFRI (003.182.92) color temperature cannot be set.

### ISSUE THREAD

**Issue by nikolajsheller** [mozilla-iot/zigbee-adapter#10] opened 2018-02-26 20:40 UTC
I have purchased the following LED to be able to have warm light during the evening and cool light during the day:
http://www.ikea.com/dk/da/catalog/products/00318292/003.182.92

The LED can be added as a dimmable bulb, and on/off state, as well as dimming, can be controlled from the IoT gateway. This is great :)

The bulb has two sets of LEDs, warm-white and cold-white that should be mixable. This is sadly not controllable yet from the IoT gateway.

**Comment by mrstegeman** [comment] 2018-02-26 20:48
We have not yet added support for this type of bulb but will be doing so in the near future.

Duplicate of https://github.com/mozilla-iot/gateway/issues/685

**Closed by mrstegeman** 2018-02-26 20:48 UTC

**Comment by nikolajsheller** [comment] 2018-02-26 21:41
Awesome. Looking toward to it bing supported.
