### ISSUE TITLE
Add support for HUSBZB-1

### ISSUE THREAD

**Issue by golden13** [mozilla-iot/zigbee-adapter#233] opened 2020-09-10 04:22 UTC
I was trying to use a USB dongle Nortek HUSBZB-1
It's a Z-Wave + Zigbee USB stick.
Silicon Labs EM3581

I got no luck. It's always saying "No Zigbee dongle found".

This is what I see in the log:
```
2020-09-10 00:09:07.547 INFO   : zigbee-adapter: DEBUG config = 'serialProber'
2020-09-10 00:09:07.548 INFO   : zigbee-adapter: Enabling DEBUG_serialProber
2020-09-10 00:09:07.789 INFO   : zigbee-adapter: SerialProber: /dev/ttyUSB0 filter for XBee didn't match.
2020-09-10 00:09:07.790 INFO   : zigbee-adapter: SerialProber: /dev/ttyUSB0 filter for deConz didn't match.
2020-09-10 00:09:07.791 INFO   : zigbee-adapter: SerialProber: /dev/ttyUSB0 filter for cc2531 didn't match.
2020-09-10 00:09:07.791 INFO   : zigbee-adapter: SerialProber: /dev/ttyUSB1 filter for XBee didn't match.
2020-09-10 00:09:07.792 INFO   : zigbee-adapter: SerialProber: /dev/ttyUSB1 filter for deConz didn't match.
2020-09-10 00:09:07.792 INFO   : zigbee-adapter: SerialProber: /dev/ttyUSB1 filter for cc2531 didn't match.
.....
2020-09-10 00:09:07.816 INFO   : zigbee-adapter: Serial ports that were found:
2020-09-10 00:09:07.917 INFO   : zigbee-adapter: USB Serial Device 10c4:8a2a Vendor: Silicon Labs Serial: C1301F44 found @ /dev/ttyUSB0
2020-09-10 00:09:07.917 INFO   : zigbee-adapter: USB Serial Device 10c4:8a2a Vendor: Silicon Labs Serial: C1301F44 found @ /dev/ttyUSB1
......
2020-09-10 00:09:07.925 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
```

Where:
/dev/ttyUSB0 - Z-Wave
/dev/ttyUSB1 - Zigbee

P.S. I did connect it successfully to OpenHab2 using their zigbee addon, but It would be nice to use Mozilla WebThings Gateway.

Thank you in advance

**Comment by mrstegeman** [comment] 2020-09-10 04:44
Duplicate of #97

**Closed by mrstegeman** 2020-09-10 04:44 UTC
